# ⚠️  CLAUDE CODE: THIS FILE IS DOTTER-MANAGED - EDIT HERE IN DOTFILES, NOT ~/.config/yazi/
# ⚠️  NEVER EDIT ~/.config/yazi/keymap.toml - IT'S A SYMLINK TO THIS FILE
# Minimal Yazi keymap - Colemak-DH navigation + Helix opening
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Colemak-DH navigation (neio)
  { on = "n", run = "leave", desc = "Go to parent directory" },
  { on = "e", run = "arrow 1", desc = "Move cursor down" },
  { on = "i", run = "arrow -1", desc = "Move cursor up" },
  { on = "o", run = "enter", desc = "Enter directory" },
  
  # File opening - three distinct modes
  { on = "<Enter>", run = "open", desc = "Open file (system default)" },
  { on = "l", run = "open --with=helix", desc = "Launch in Helix (current pane)" },
  { on = "L", run = """shell 'zellij action new-pane -- hx "$@"' --block""", desc = "Open in Helix (new pane)" },
  { on = "h", run = "open --interactive", desc = "How to open? (interactive picker)" },
  
  # Project-aware search functions (requires Full Disk Access + Developer Tools for WezTerm)
  { on = "s", run = """shell 'zellij action new-pane --floating --close-on-exit --width 90% --height 85% -- nu $HOME/.local/bin/zellij-skim-search.nu' --block""", desc = "Search: skim with full TTY environment" },
  { on = [ "s", "p" ], run = """shell 'zellij run --direction right --close-on-exit -- nu $HOME/.local/bin/yazi-project-file-search-floating.nu' --block""", desc = "Search: regular Pane (zellij run)" },
  { on = [ "s", "t" ], run = """shell 'zellij action new-tab --name "File Search"; zellij run -- nu $HOME/.local/bin/yazi-project-file-search-floating.nu' --block""", desc = "Search: new Tab (zellij run)" },
  { on = "S", run = """shell 'zellij action new-pane --close-on-exit --floating --width 90% --height 85% -- bash -c "echo -n \"Search (use AND/OR for multiple terms): \"; read term; selected=$(nu $HOME/.local/bin/yazi-project-content-search.nu \"$term\"); [ -n \"$selected\" ] && hx \"$selected\""' --block""", desc = "Project-aware content search with floating pane" },
  { on = "R", run = """shell 'zellij action new-pane --close-on-exit --floating --width 90% --height 85% -- nu $HOME/.local/bin/yazi-recent-files.nu' --block""", desc = "Recent files (last 7 days) with floating pane" },
  # Quick navigation shortcuts (g prefix)
  { on = [ "g", "g" ], run = "arrow -999999999", desc = "Go to top" },
  { on = [ "g", "e" ], run = "arrow 999999999", desc = "Go to bottom" },
  { on = [ "g", "h" ], run = "cd ~", desc = "Go to home directory" },
  { on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Go to Downloads" },
  { on = [ "g", "c" ], run = "cd ~/.config", desc = "Go to config directory" },
  { on = [ "g", "n" ], run = "shell 'nu -c \"source ~/.config/nushell/config.nu; cd (detect-forge)\"' --block", desc = "Go to Forge (cross-platform)" },
  
  # Zoxide frecency-based directory jumping (lowercase z)
  { on = "z", run = "shell '$HOME/.local/bin/yazi-zoxide-jump' --block --confirm", desc = "Zoxide frecency jump with skim" },
  # General directory search (uppercase Z)  
  { on = "Z", run = "shell '$HOME/.local/bin/yazi-directory-jump' --block --confirm", desc = "General directory picker with Nushell preview" },
  
  # Basic file operations
  { on = "y", run = "yank", desc = "Copy" },
  
  # Zotero import - select PDFs and press I (Import) to add to Zotero
  { on = "I", run = """shell 'for file in "$@"; do $HOME/.local/bin/zotero-cli-import "$file" --move; done' --block --confirm""", desc = "Import PDFs to Zotero" },
  
  # Quick daily note access  
  { on = "D", run = """shell '$HOME/.local/bin/daily-note' --block""", desc = "Open today's daily note" },
  
  # Forge wiki link navigation
  { on = "b", run = """shell 'nu ~/.config/yazi/scripts/show-backlinks.nu' --block --confirm""", desc = "Show backlinks to current note" },
  { on = "f", run = """shell 'nu ~/.config/yazi/scripts/show-links.nu' --block --confirm""", desc = "Show forward links from current note" },
  
  { on = "p", run = "paste", desc = "Paste" },
  { on = "d", run = "remove", desc = "Delete" },
  { on = "a", run = "create", desc = "Create" },
  { on = "r", run = "rename", desc = "Rename" },
]