# Minimal Yazi keymap - Colemak-DH navigation + Helix opening
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Colemak-DH navigation (neio)
  { on = "n", run = "leave", desc = "Go to parent directory" },
  { on = "e", run = "arrow 1", desc = "Move cursor down" },
  { on = "i", run = "arrow -1", desc = "Move cursor up" },
  { on = "o", run = "enter", desc = "Enter directory" },
  
  # File opening - l for "launch" in Helix (maintains terminal context)
  { on = "<Enter>", run = "open", desc = "Open file (system default)" },
  { on = "l", run = """shell --block --confirm 'hx "$@"'""", desc = "Open in Helix (edit mode)" },
  { on = "h", run = "open --interactive", desc = "Choose how to open (picker)" },
  
  # File search with multi-select and better defaults
  { on = "s", run = """shell 'unset TERMINFO && unset TERMINFO_DIRS && export TERM=xterm && /opt/homebrew/bin/fd -t f | /opt/homebrew/bin/sk --multi --bind="tab:toggle+down,ctrl-a:select-all" --preview "FILE_PATH={} /Users/williamnapier/.config/yazi/scripts/file-preview.nu" | xargs hx' --block""", desc = "Smart file search (Nushell tables)" },
  { on = "S", run = """shell 'cd "$0" && rg -l . | sk --preview "FILE_PATH={} /Users/williamnapier/.config/yazi/scripts/search-preview.nu" | xargs -r hx' --block""", desc = "Content search (Nushell tables)" },
  { on = "z", run = "plugin zoxide", desc = "Jump to directory (zoxide frecency)" },
  { on = "Z", run = """shell 'fd -t d | sk --preview "FILE_PATH={} /Users/williamnapier/.config/yazi/scripts/dir-preview.nu" | xargs -r hx' --block""", desc = "Directory picker (Nushell tables)" },
  
  # Basic file operations
  { on = "y", run = "yank", desc = "Copy" },
  { on = "p", run = "paste", desc = "Paste" },
  { on = "d", run = "remove", desc = "Delete" },
  { on = "a", run = "create", desc = "Create" },
  { on = "r", run = "rename", desc = "Rename" },
]