# Minimal Yazi keymap - Colemak-DH navigation + Helix opening
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Colemak-DH navigation (neio)
  { on = "n", run = "leave", desc = "Go to parent directory" },
  { on = "e", run = "arrow 1", desc = "Move cursor down" },
  { on = "i", run = "arrow -1", desc = "Move cursor up" },
  { on = "o", run = "enter", desc = "Enter directory" },
  
  # File opening - l for "launch" in Helix (maintains terminal context)
  { on = "<Enter>", run = "open", desc = "Open file (system default)" },
  { on = "l", run = """shell 'hx "$@"' --block --confirm""", desc = "Open in Helix (edit mode)" },
  { on = "h", run = "open --interactive", desc = "Choose how to open (picker)" },
  
  # Basic file operations
  { on = "y", run = "yank", desc = "Copy" },
  { on = "p", run = "paste", desc = "Paste" },
  { on = "d", run = "remove", desc = "Delete" },
  { on = "a", run = "create", desc = "Create" },
  { on = "r", run = "rename", desc = "Rename" },
]