# Helix Configuration for Colemak-DH

# Use standard Solarized themes - change based on system appearance
# For dark mode: theme = "solarized_light" 
# For light mode: theme = "solarized_light"
# Modal versions with mode indicators: "solarized_dark_modal" or "solarized_light_modal"
theme = "solarized_light_modal"

[editor]
# Enable cursor shape changing
cursorline = true

# Soft wrap configuration
[editor.soft-wrap]
enable = true
max-wrap = 25  # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set to "" to hide wrap indicator

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# Navigation (neio for hjkl)
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"

# Displaced commands
h = "open_below"           # was on 'o'
j = "search_next"          # was on 'n'
k = "move_next_word_end"   # was on 'e'
l = "find_till_char"       # was on 't' (tilL)
t = "insert_mode"          # was on 'i' (inserT)

# Shifted versions for consistency
N = "extend_char_left"     # extend version of 'n'
E = "extend_line_down"     # extend version of 'e'
I = "extend_line_up"       # extend version of 'i'
O = "extend_char_right"    # extend version of 'o'
H = "open_above"           # pair with 'h' (open_below)
J = "search_prev"          # pair with 'j' (search_next)
K = "extend_next_word_end" # extend version of 'k'
L = "till_prev_char"       # pair with 'l' (till forward)
T = "insert_at_line_start"  # was on 'I' (Insert at line start)

# Quick wiki link navigation - Space+w to follow wiki links
[keys.normal.space]
w = ["extend_to_line_bounds", ":pipe-to hx-wiki", ":open /tmp/helix-current-link.md"]
# Toggle todo checkbox - Space+t
t = ["extend_to_line_bounds", ":pipe-to sed 's/\\[ \\]/[x]/g; s/\\[x\\]/[ ]/g'"]

# Custom commands for opening URLs and wiki links
[keys.normal.g]
# gx - Open URLs in browser (place cursor on URL)
x = ["extend_to_line_bounds", ":pipe-to bash -c 'grep -oE \"https?://[^[:space:]<>]+|www\\.[^[:space:]<>]+\" | head -1 | xargs open'"]
# gw - Process wiki link and copy path to clipboard (then :o Cmd+V to open)
w = ["extend_to_line_bounds", ":pipe-to hx-wiki"]
# gW - Combined: process wiki link and open it (single command!)
W = ["extend_to_line_bounds", ":pipe-to hx-wiki", ":open /tmp/helix-current-link.md"]

[keys.select]
# Same navigation in select mode
n = "extend_char_left"
e = "extend_line_down"
i = "extend_line_up"
o = "extend_char_right"

# Displaced commands in select mode
h = "open_below"
j = "search_next"
k = "extend_next_word_end"
l = "find_till_char"       # was on 't' (tilL)
L = "till_prev_char"       # was on 'T' (till backward)
t = "insert_mode"          # was on 'i' (inserT)
T = "insert_at_line_start"  # was on 'I' (Insert at line start)