# ⚠️  CLAUDE CODE: THIS FILE IS DOTTER-MANAGED - EDIT HERE IN DOTFILES, NOT ~/.config/helix/
# ⚠️  NEVER EDIT ~/.config/helix/config.toml - IT'S A SYMLINK TO THIS FILE
# Helix Configuration for Colemak-DH
# Sync test: $(date)

# Use standard Solarized themes - change based on system appearance
# For dark mode: theme = "solarized_dark" 
# For light mode: theme = "solarized_dark"
# Modal versions with mode indicators: "solarized_dark_modal" or "solarized_light_modal"
theme = "solarized_dark_modal"

[editor]
# Enable cursor shape changing
cursorline = true
# Auto-save files when switching buffers or after inactivity
auto-save = true
# Auto-save every 500ms for activity duration processing (prevents race conditions)
idle-timeout = 500

# Status line configuration
[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type"]

# Soft wrap configuration
[editor.soft-wrap]
enable = true
max-wrap = 25  # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set to "" to hide wrap indicator

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# Navigation (neio for hjkl)
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"

# Fix for ZMK keyboard key interpretation in WezTerm
# These explicit bindings ensure correct behavior regardless of terminal interpretation
# ZMK sends US layout keycodes, macOS expects British layout, causing symbol misinterpretation
# This is a stable solution - no need to modify ZMK firmware (2025-09-09)
"$" = "goto_line_end"              # End of line
"0" = "goto_line_start"            # Beginning of line  
"^" = "goto_first_nonwhitespace"   # First non-whitespace
"%" = "match_brackets"              # Match bracket
"_" = "goto_first_nonwhitespace"   # Also first non-whitespace (alternate)
"|" = "goto_column"                 # Go to column
"*" = "search_selection"            # Search for selection
"#" = "search_prev"                 # Search backwards
"&" = "shell_keep_pipe"             # Ensure & works correctly for its intended purpose

# Displaced commands
h = "open_below"           # was on 'o'
j = "search_next"          # was on 'n'
k = "move_next_word_end"   # was on 'e'
l = "find_till_char"       # was on 't' (tilL)
t = "insert_mode"          # was on 'i' (inserT)

# Shifted versions for consistency
N = "extend_char_left"     # extend version of 'n'
E = "extend_line_down"     # extend version of 'e'
I = "extend_line_up"       # extend version of 'i'
O = "extend_char_right"    # extend version of 'o'
H = "open_above"           # pair with 'h' (open_below)
J = "search_prev"          # pair with 'j' (search_next)
K = "extend_next_word_end" # extend version of 'k'
L = "till_prev_char"       # pair with 'l' (till forward)
T = "insert_at_line_start"  # was on 'I' (Insert at line start)

[keys.normal.space]
# Toggle todo checkbox - Space+t (3-state: no checkbox → unchecked → checked → unchecked)
t = ["extend_to_line_bounds", ":pipe hx-toggle-todo"]

# Manual theme refresh - Space+T (capital T)  
T = ":config-reload"
# Process activity durations - WezTerm auto-refresh (fully automated)
p = [":write!", ":sh sleep 1 && sync", ":sh hx-process-durations-wezterm %{buffer_name}"]
# Delete current file - Space+x (eXpunge, no confirmation)
x = [":sh trash %{buffer_name}", ":quit!"]
# Export selection to external register - Space+E (then type register letter)
E = ":pipe-to hx-register-export"
# Wiki link navigation - Space+w (auto-exports + tracks history for wb)
# Critical: move_next_word_start moves cursor off column 0 to prevent extend_to_line_bounds selecting previous line
w = [":sh echo %{buffer_name} > /tmp/helix-current-file.txt", ":sh echo %{buffer_name} >> /tmp/wiki-nav-history.txt", ":write", "move_next_word_start", "move_prev_word_start", ":sh echo %{selection.column.0} > /tmp/helix-cursor-col.txt", "extend_to_line_bounds", ":pipe-to ~/.local/bin/hx-wiki", ":open /tmp/helix-current-link.md"]
# Smart file opener - Space+o (handles all file types and wiki links)
o = ["extend_to_line_bounds", ":pipe-to hx-open-system-rust"]  # Open in system app (Preview, Excel, etc.)
# Fuzzy link insertion - Space+l (Zellij floating pane)
# Note: Use Alt+l in Zellij for floating pane link picker
# Then paste result with standard paste command
l = ":insert-output pbpaste"
# Show real file name - Space+i (Info about current file)
i = ":sh hx-show-real-file %{buffer_name}"
# Quick save commands - Space+m ("memorize" or "save to memory")
m = ":write"         # Quick save current file
M = ":write-all"     # Save all modified files

# Date and time insertion - Space+c ("calendar" or "chronos")
# Moved from Space+d to avoid conflict with diagnostic picker (important for Rust LSP)
c = ":insert-output hx-insert-date"        # Insert current date (YYYY-MM-DD)
# Time insertion moved to avoid conflicts with Space+t (todo toggle) and Space+T (config reload)
";" = ":insert-output hx-insert-time"      # Insert current time (HH:MM) 
":" = ":insert-output hx-insert-datetime"  # Insert date and time (YYYY-MM-DD HH:MM)
# Mark file as revisited - using 'v' for 'visited'
v = ":sh hx-mark-revisit %{buffer_name}"   # Add today to revisited dates

# Removed: Space+. export (wiki-nav now auto-detects most recent file)

# Buffer navigation - Space+b for back (intuitive)
b = [":write-all", "goto_previous_buffer", ":sh sleep 0.5", ":reload-all"]  # Save all, go back, wait for backlinks, reload all

# Save and return to previous buffer - Space+q
q = [":write", ":buffer-previous"]       # Save then go to previous buffer
Q = ":quit!"                                # Force quit without saving

# Custom g-prefix commands
[keys.normal.g]
f = ["extend_to_line_bounds", ":pipe-to hx-smart-gf-rust", ":open /tmp/helix-gf-target.md"]  # Smart file opener (Rust/Nushell version with fd, rg)
x = ["extend_to_line_bounds", ":pipe-to hx-open-url"]  # Open URLs
w = ["extend_to_line_bounds", ":pipe-to hx-wiki", ":open /tmp/helix-current-link.md"]  # Wiki link navigation (opens via temp symlink)

# Serpl search and replace integration - Space+r,r
[keys.normal.space.r]
r = [
  ":write-all",
  ":sh git add -A && git commit -m 'pre-serpl snapshot' || true",
  ":insert-output nu -c 'serpl-anywhere >/dev/tty'",
  ":redraw",
  ":reload-all"
]

[keys.select]
# Same navigation in select mode
n = "extend_char_left"
e = "extend_line_down"
i = "extend_line_up"
o = "extend_char_right"

# Displaced commands in select mode
h = "open_below"
j = "search_next"
k = "extend_next_word_end"
l = "find_till_char"       # was on 't' (tilL)
L = "till_prev_char"       # was on 'T' (till backward)
t = "insert_mode"          # was on 'i' (inserT)
T = "insert_at_line_start"  # was on 'I' (Insert at line start)
