#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=32 blur_radius=30 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$ICON_COLOR
  label.color=$LABEL_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
source "$ITEM_DIR/aerospace.sh"

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off

##### Right Side Items #####
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
