//! The House Model: Will's practice against the flat decision and the June-2027
//! remortgage. Source of truth is the .fods generated by
//! `~/Assistants/shared/house-model/build_house_model.py`; the .xlsx beside it
//! is the machine-read copy. This module never writes to either.

use crate::book::{markdown_table, parse_target, Book, Pos, Target};
use crate::live;
use anyhow::{bail, Context, Result};
use chrono::{Local, NaiveDate};
use serde::Serialize;
use std::path::PathBuf;

pub const FILE_PREFIX: &str = "Scenario - The House Model";

/// Short aliases for Assumptions rows, resolved by column-A label substring.
/// If Seneca renames a label the alias fails loudly with the candidates.
pub const ALIASES: &[(&str, &str)] = &[
    ("fee", "Realised fee per SSE"),
    ("weeks", "Earning weeks per year"),
    ("remote_weeks", "Of which remote-only weeks"),
    ("remote_frac", "Sessions kept in a remote-only week"),
    ("roof", "Planning roof"),
    ("salary", "Director's salary"),
    ("rent3", "Rooms: rent"),
    ("leigh", "Leigh's fee"),
    ("motor", "Motor vehicle"),
    ("other_costs", "Other recurring"),
    ("pension_allowance", "Pension annual allowance"),
    ("pa", "Personal allowance"),
    ("basic_band", "Basic-rate band"),
    ("cap", "Draw cap"),
    ("base_life", "Somerset life ex-mortgage"),
    ("flat_running", "Flat running costs"),
    ("ct_premium", "Ealing second-home"),
    ("premium_share", "Share of the premium"),
    ("london_transport", "London transport"),
    ("london_food", "London food"),
    ("london_cash", "London cash"),
    ("trips_if_sold", "Voluntary London trips"),
    ("heating_if_sold", "Extra Forge heating"),
    ("nights", "London nights per London week"),
    ("room", "Room rate per night"),
    ("train", "Taunton–Paddington"),
    ("parking", "Taunton station parking"),
    ("forge_bal", "Forge balance"),
    ("flat_bal", "Flat balance"),
    ("rate", "New rate (both loans)"),
    ("rate_now", "Current blended rate"),
    ("jenny_share", "Jenny's share of mortgage"),
    ("capital", "Capital element"),
    ("proceeds", "Net flat proceeds"),
    ("shares", "Tesla shares"),
    ("tsla", "Tesla price today"),
    ("fx", "£ per $"),
    ("sjp", "Non-Tesla sleeve today"),
    ("sjp_g", "Growth on the non-Tesla"),
    ("tsla_g", "Growth on Tesla"),
    ("years", "Years to June 2032"),
    ("chimney_in", "Chimney: pension contribution"),
    ("draw_pct", "Pension draw in 2032"),
    ("state_pension", "State pension from"),
    ("clear_flat", "Pot at which the lump"),
    ("lsa", "Lump-sum allowance"),
];

/// The rows of Lives that make up "the house", found by column-A label prefix.
const HOUSE_ROWS: &[(&str, &str)] = &[
    ("Floor", "FLOOR"),
    ("Ceiling", "CEILING"),
    ("Leeway", "LEEWAY"),
    ("Roof", "Roof ("),
    ("Chimney (sessions)", "Sessions above the ceiling"),
    ("Chimney to pension (£)", "Of which the pension can take"),
    ("Solvency margin", "Solvency margin"),
    ("Will's living, net (£)", "Will's living, net"),
    ("Spendable room under cap (£)", "Spendable room under the cap"),
    ("Pence kept per £ past cap", "Pence kept per £"),
];

/// Expand `fee=180` into `Assumptions@Realised fee per SSE=180`; pass anything else through.
pub fn expand_alias(s: &str) -> String {
    let Some(eq) = s.find('=') else { return s.to_string() };
    let key = s[..eq].trim();
    for (alias, label) in ALIASES {
        if key.eq_ignore_ascii_case(alias) {
            return format!("Assumptions@{label}{}", &s[eq..]);
        }
    }
    s.to_string()
}

/// Newest `~/Forge/Scenario - The House Model*.xlsx`.
pub fn default_file() -> Result<PathBuf> {
    let forge = dirs::home_dir().context("no home dir")?.join("Forge");
    let mut hits: Vec<(std::time::SystemTime, PathBuf)> = std::fs::read_dir(&forge)
        .with_context(|| format!("reading {}", forge.display()))?
        .flatten()
        .filter(|e| {
            let n = e.file_name().to_string_lossy().to_string();
            n.starts_with(FILE_PREFIX) && n.ends_with(".xlsx")
        })
        .filter_map(|e| Some((e.metadata().ok()?.modified().ok()?, e.path())))
        .collect();
    hits.sort();
    hits.pop().map(|(_, p)| p).with_context(|| format!("no '{FILE_PREFIX}*.xlsx' in {}", forge.display()))
}

#[derive(Debug, Serialize)]
pub struct HouseRow {
    pub item: String,
    pub values: Vec<String>,
    pub numbers: Vec<Option<f64>>,
}

#[derive(Debug, Serialize)]
pub struct House {
    pub file: String,
    pub columns: Vec<String>,
    pub rows: Vec<HouseRow>,
    pub overrides: Vec<(String, Option<String>, String, String)>,
    pub missing: Vec<String>,
}

pub fn read_house(book: &Book, overrides: Vec<(String, Option<String>, String, String)>) -> Result<House> {
    let lives = book.sheet_index("Lives")?;
    let (_, _, min_col, max_col) = book.dimension(lives)?;
    let cols: Vec<i32> = ((min_col.max(2))..=max_col).collect();
    let columns: Vec<String> = cols.iter().map(|c| book.formatted(Pos { sheet: lives, row: 1, col: *c })).collect();
    let mut rows = vec![];
    let mut missing = vec![];
    for (item, prefix) in HOUSE_ROWS {
        match book.find_label_row(lives, prefix) {
            Ok(r) => {
                let values = cols.iter().map(|c| book.formatted(Pos { sheet: lives, row: r, col: *c })).collect();
                let numbers = cols.iter().map(|c| book.number(Pos { sheet: lives, row: r, col: *c })).collect();
                rows.push(HouseRow { item: item.to_string(), values, numbers });
            }
            Err(_) => missing.push(format!("{item} (label '{prefix}')")),
        }
    }
    Ok(House { file: book.path.clone(), columns, rows, overrides, missing })
}

pub fn render_house(h: &House) -> String {
    let mut out = String::new();
    out.push_str(&format!("The House Model — {}\n\n", h.file));
    let mut header = vec!["Lives".to_string()];
    header.extend(h.columns.iter().cloned());
    let rows: Vec<Vec<String>> = h.rows.iter().map(|r| {
        let mut v = vec![r.item.clone()];
        v.extend(r.values.iter().cloned());
        v
    }).collect();
    out.push_str(&markdown_table(&header, &rows));
    if !h.overrides.is_empty() {
        out.push_str("\nWhat-if overrides (in memory only, the file is untouched):\n");
        for (r, label, before, after) in &h.overrides {
            out.push_str(&format!("- {}{}: {} → {}\n", r, label.as_ref().map(|l| format!(" ({l})")).unwrap_or_default(), before, after));
        }
    }
    if !h.missing.is_empty() {
        out.push_str("\nRows not found on Lives (the generator may have renamed them):\n");
        for m in &h.missing {
            out.push_str(&format!("- {m}\n"));
        }
    }
    out
}

fn assumption(book: &Book, alias: &str) -> Option<f64> {
    let t = parse_target(&expand_alias(&format!("{alias}=0")).trim_end_matches("=0").to_string()).ok()?;
    if let Target::Label { .. } = t {
        book.number(book.resolve(&t).ok()?)
    } else {
        None
    }
}

#[derive(Debug, Serialize)]
pub struct DriftRow {
    pub item: String,
    pub model: Option<f64>,
    pub live: Option<f64>,
    pub source: String,
}

#[derive(Debug, Serialize)]
pub struct Drift {
    pub today: NaiveDate,
    pub rows: Vec<DriftRow>,
    pub notes: Vec<String>,
    pub report: Option<live::BillingReport>,
    pub cashflow_warnings: Vec<String>,
    pub spend: Option<live::SpendFloor>,
    pub failures: Vec<String>,
}

/// Compare the model's calibration inputs with the live sources. Each source
/// that fails is reported, not fatal, so a Xero token lapse does not hide the
/// fd-budget figure or vice versa.
pub fn drift(book: &Book, report_from: Option<NaiveDate>, spend_since: Option<NaiveDate>) -> Drift {
    let today = Local::now().date_naive();
    let mut rows = vec![];
    let mut notes = vec![];
    let mut failures = vec![];

    let from = report_from.unwrap_or_else(|| live::default_report_from(today));
    let report = match live::fetch_billing_report(from, today) {
        Ok(r) => Some(r),
        Err(e) => { failures.push(format!("practiceforge billing report: {e:#}")); None }
    };
    if let Some(r) = &report {
        let src = format!("Xero via practiceforge, {} to {} ({:.0} SSE)", r.period_start, r.period_end, r.session_equivalents);
        rows.push(DriftRow { item: "Fee per SSE (£)".into(), model: assumption(book, "fee"), live: r.fee_per_sse(), source: src.clone() });
        if let Some(ew) = &r.earning_week {
            rows.push(DriftRow { item: "SSE per earning week (mean) vs planning roof".into(), model: assumption(book, "roof"), live: Some(ew.sse_per_earning_week_mean), source: format!("{} earning weeks in the window", ew.earning_weeks) });
            rows.push(DriftRow { item: "SSE per earning week (median)".into(), model: None, live: Some(ew.sse_per_earning_week_median), source: src.clone() });
        }
        rows.push(DriftRow { item: "SSE per calendar week".into(), model: None, live: Some(r.average_sse_per_week), source: src });
    }

    let mut cashflow_warnings = vec![];
    match live::fetch_cashflow() {
        Ok(c) => {
            cashflow_warnings = c.warnings.clone();
            let as_of = c.live_expenses.as_ref().and_then(|l| l.as_of.clone()).unwrap_or_default();
            let src = format!("Xero P&L via practiceforge cashflow, FY to {as_of}");
            rows.push(DriftRow { item: "Rooms rent, 3 London days (£/yr)".into(), model: assumption(book, "rent3"), live: c.account("Rent"), source: src.clone() });
            let motor_recurring = c.account("Motor Vehicle Expenses").map(|m| m - c.live_expenses.as_ref().and_then(|l| l.one_off_stripped).unwrap_or(0.0));
            rows.push(DriftRow { item: "Motor, recurring (£/yr)".into(), model: assumption(book, "motor"), live: motor_recurring, source: format!("{src}; one-off wrap stripped") });
            rows.push(DriftRow { item: "Other recurring small lines (£/yr)".into(), model: assumption(book, "other_costs"), live: c.small_lines(), source: format!("{src}; bad debt, pension, CT excluded") });
            rows.push(DriftRow { item: "practiceforge going-concern floor (SSE/wk)".into(), model: None, live: Some(c.floor_fund_life_only), source: format!("practiceforge cashflow at living £{:.0}; different living basis from the model", c.net_living_funded) });
        }
        Err(e) => failures.push(format!("practiceforge billing cashflow: {e:#}")),
    }

    let since = spend_since.unwrap_or_else(|| live::default_spend_since(today));
    let spend = match live::fetch_spend_floor(since) {
        Ok(s) => Some(s),
        Err(e) => { failures.push(format!("fd-budget stats: {e:#}")); None }
    };
    if let Some(s) = &spend {
        let living = book.sheet_index("Lives").ok().and_then(|l| book.find_label_row(l, "Will's living, net").ok().map(|r| Pos { sheet: l, row: r, col: 2 })).and_then(|p| book.number(p));
        rows.push(DriftRow { item: "Personal living, annualised (£/yr) vs model keep-flat".into(), model: living, live: Some(s.spend_annualised()), source: format!("fd-budget spend floor {} to {}; model row is Will's living, net incl. mortgage share", s.from, s.to) });
        let stale = s.stale_days(today);
        if stale > 30 {
            notes.push(format!("fd-budget data ends {} ({stale} days ago) — import fresh midata before trusting the living figure", s.to));
        }
        if s.untagged_debits > 0 {
            notes.push(format!("fd-budget: {} untagged debits still counted as spend", s.untagged_debits));
        }
    }
    Drift { today, rows, notes, report, cashflow_warnings, spend, failures }
}

fn fmt_opt(v: Option<f64>) -> String {
    match v {
        None => "".into(),
        Some(x) if x.abs() >= 1000.0 => {
            let s = format!("{:.0}", x);
            let mut out = String::new();
            for (i, ch) in s.chars().rev().enumerate() {
                if i > 0 && i % 3 == 0 && ch != '-' { out.push(','); }
                out.push(ch);
            }
            out.chars().rev().collect()
        }
        Some(x) if x.abs() >= 100.0 => format!("{:.1}", x),
        Some(x) => format!("{:.2}", x),
    }
}

pub fn render_drift(d: &Drift) -> String {
    let mut out = String::new();
    out.push_str(&format!("\nModel vs live ({})\n\n", d.today));
    let header = ["Item", "Model", "Live", "Δ", "Source"].map(String::from);
    let rows: Vec<Vec<String>> = d.rows.iter().map(|r| {
        let delta = match (r.model, r.live) { (Some(m), Some(l)) => fmt_opt(Some(l - m)), _ => "".into() };
        vec![r.item.clone(), fmt_opt(r.model), fmt_opt(r.live), delta, r.source.clone()]
    }).collect();
    out.push_str(&markdown_table(&header, &rows));
    for n in &d.notes { out.push_str(&format!("- note: {n}\n")); }
    for w in &d.cashflow_warnings { out.push_str(&format!("- practiceforge: {w}\n")); }
    for f in &d.failures { out.push_str(&format!("- FAILED: {f}\n")); }
    out
}

/// `--apply-live`: turn the live fee (and roof, from the earning-week mean) into overrides.
pub fn live_overrides(d: &Drift) -> Result<Vec<String>> {
    let r = d.report.as_ref().context("no live billing report to apply")?;
    let mut v = vec![];
    if let Some(fee) = r.fee_per_sse() { v.push(format!("fee={:.2}", fee)); }
    if let Some(ew) = &r.earning_week { v.push(format!("roof={:.1}", ew.sse_per_earning_week_mean)); }
    if v.is_empty() { bail!("live report carried no fee or roof to apply"); }
    Ok(v)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn aliases_expand_to_label_targets() {
        assert_eq!(expand_alias("fee=180"), "Assumptions@Realised fee per SSE=180");
        assert_eq!(expand_alias("RATE=5.5%"), "Assumptions@New rate (both loans)=5.5%");
        assert_eq!(expand_alias("Lives!B2=3"), "Lives!B2=3");
        assert_eq!(expand_alias("Assumptions@Leigh=12000"), "Assumptions@Leigh=12000");
        assert_eq!(expand_alias("nonsense"), "nonsense");
    }

    #[test]
    fn aliases_are_unique() {
        let mut seen = std::collections::HashSet::new();
        for (a, _) in ALIASES { assert!(seen.insert(*a), "duplicate alias {a}"); }
    }

    #[test]
    fn thousands_formatting() {
        assert_eq!(fmt_opt(Some(36100.0)), "36,100");
        assert_eq!(fmt_opt(Some(-1234.6)), "-1,235");
        assert_eq!(fmt_opt(Some(173.24)), "173.2");
        assert_eq!(fmt_opt(Some(32.676)), "32.68");
        assert_eq!(fmt_opt(None), "");
    }
}
