use crate::gf256;

/// Generate a self-contained HTML reconstruction page.
///
/// The page includes inline JavaScript implementing the same GF(256) Shamir
/// reconstruction as the Rust code. GF(256) tables are injected from Rust
/// to guarantee identical arithmetic.
pub fn generate_reconstruction_html() -> String {
    let exp = gf256::exp_table_json();
    let log = gf256::log_table_json();

    format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bequest — Secret Reconstruction</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;
  max-width:700px;margin:2rem auto;padding:0 1.5rem;
  color:#1a1a1a;line-height:1.6;background:#fafafa;
}}
h1{{margin-bottom:0.25rem;font-size:1.8rem}}
.subtitle{{color:#666;margin-bottom:2rem}}
.info{{
  background:#f0f4f8;border-left:4px solid #4a90d9;
  padding:1rem 1.25rem;margin-bottom:2rem;border-radius:0 4px 4px 0;
}}
.info p{{margin-bottom:0.5rem}}
.info p:last-child{{margin-bottom:0}}
.share-group{{margin-bottom:1rem}}
.share-group label{{display:block;font-weight:600;margin-bottom:0.25rem}}
textarea{{
  width:100%;height:4.5rem;
  font-family:'SF Mono','Fira Code',Consolas,monospace;font-size:0.85rem;
  padding:0.75rem;border:2px solid #d0d0d0;border-radius:6px;resize:vertical;
}}
textarea:focus{{border-color:#4a90d9;outline:none}}
.btns{{margin:1.5rem 0;display:flex;gap:0.75rem;flex-wrap:wrap}}
button{{
  padding:0.75rem 1.5rem;border:none;border-radius:6px;
  font-size:1rem;cursor:pointer;font-weight:600;
}}
.bp{{background:#2563eb;color:#fff}}
.bp:hover{{background:#1d4ed8}}
.bs{{background:#e5e7eb;color:#374151}}
.bs:hover{{background:#d1d5db}}
#output{{
  display:none;margin-top:2rem;background:#ecfdf5;
  border:2px solid #10b981;border-radius:8px;padding:1.5rem;
}}
#output h2{{font-size:1.2rem;margin-bottom:0.75rem;color:#065f46}}
#secret-output{{
  background:#fff;padding:1rem;border-radius:4px;
  font-family:'SF Mono','Fira Code',Consolas,monospace;font-size:0.9rem;
  white-space:pre-wrap;word-break:break-all;border:1px solid #d1fae5;
}}
#error{{
  display:none;margin-top:1.5rem;background:#fef2f2;
  border:2px solid #ef4444;border-radius:8px;padding:1rem 1.25rem;color:#991b1b;
}}
.copy-btn{{margin-top:0.75rem}}
.pn{{
  margin-top:3rem;padding-top:1.5rem;border-top:1px solid #e5e7eb;
  color:#6b7280;font-size:0.85rem;
}}
</style>
</head>
<body>
<h1>Bequest</h1>
<p class="subtitle">Secret Reconstruction</p>

<div class="info">
  <p><strong>Instructions:</strong> Each trustee should paste their share into a
  separate box below. You need the required number of shares (the threshold) to
  reconstruct the secret.</p>
  <p>This page works entirely offline &mdash; no data leaves your browser.</p>
</div>

<div id="shares"></div>

<div class="btns">
  <button class="bs" onclick="addField()">+ Add share</button>
  <button class="bp" onclick="doReconstruct()">Reconstruct Secret</button>
</div>

<div id="output">
  <h2>Recovered Secret</h2>
  <pre id="secret-output"></pre>
  <button class="bs copy-btn" onclick="copySecret()">Copy to clipboard</button>
</div>

<div id="error"><p id="error-msg"></p></div>

<p class="pn">
  This is a self-contained page. All cryptographic operations run locally in your
  browser. No network requests are made. You can verify by disconnecting from the
  internet before use.
</p>

<script>
// GF(256) tables — generated by Rust, identical to the Rust implementation
const EXP={exp};
const LOG={log};

function gfAdd(a,b){{return a^b}}
function gfMul(a,b){{
  if(a===0||b===0)return 0;
  return EXP[(LOG[a]+LOG[b])%255];
}}
function gfDiv(a,b){{
  if(b===0)throw new Error("division by zero");
  if(a===0)return 0;
  return EXP[((LOG[a]-LOG[b])+255)%255];
}}

function lagrangeAtZero(xs,ys){{
  let r=0;
  const k=xs.length;
  for(let i=0;i<k;i++){{
    let num=1,den=1;
    for(let j=0;j<k;j++){{
      if(i===j)continue;
      num=gfMul(num,xs[j]);
      den=gfMul(den,gfAdd(xs[i],xs[j]));
    }}
    r=gfAdd(r,gfMul(ys[i],gfDiv(num,den)));
  }}
  return r;
}}

function parseShare(text){{
  const cleaned=text.trim().replace(/^Share\s+\d+.*?:\s*/i,'');
  const bin=atob(cleaned);
  const bytes=new Uint8Array(bin.length);
  for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);
  return bytes;
}}

function doReconstruct(){{
  try{{
    const areas=document.querySelectorAll('.si');
    const shares=[];
    for(const ta of areas){{
      const v=ta.value.trim();
      if(!v)continue;
      shares.push(parseShare(v));
    }}
    if(shares.length===0){{showErr("No shares entered.");return}}
    const slen=shares[0].length-1;
    for(const s of shares){{
      if(s.length-1!==slen){{
        showErr("Shares have different lengths — they may be from different secrets.");
        return;
      }}
    }}
    const xs=shares.map(s=>s[0]);
    const secret=new Uint8Array(slen);
    for(let b=0;b<slen;b++){{
      const ys=shares.map(s=>s[1+b]);
      secret[b]=lagrangeAtZero(xs,ys);
    }}
    document.getElementById('secret-output').textContent=new TextDecoder().decode(secret);
    document.getElementById('output').style.display='block';
    document.getElementById('error').style.display='none';
  }}catch(e){{
    showErr("Reconstruction failed: "+e.message);
  }}
}}

let sc=0;
function addField(){{
  sc++;
  const d=document.createElement('div');
  d.className='share-group';
  d.innerHTML='<label>Share '+sc+'</label><textarea class="si" placeholder="Paste share here…"></textarea>';
  document.getElementById('shares').appendChild(d);
}}
function showErr(m){{
  document.getElementById('error-msg').textContent=m;
  document.getElementById('error').style.display='block';
  document.getElementById('output').style.display='none';
}}
function copySecret(){{
  const t=document.getElementById('secret-output').textContent;
  navigator.clipboard.writeText(t).then(()=>{{
    const btn=document.querySelector('.copy-btn');
    const orig=btn.textContent;
    btn.textContent='Copied!';
    setTimeout(()=>btn.textContent=orig,2000);
  }});
}}

addField();addField();
</script>
</body>
</html>"##,
        exp = exp,
        log = log,
    )
}
