[symlinks]
"aerospace/aerospace.toml" = "/Users/williamnapier/.config/aerospace/aerospace.toml"
"ghostty/config" = "/Users/williamnapier/Library/Application Support/com.mitchellh.ghostty/config"
"ghostty/themes/solarized-dark" = "/Users/williamnapier/.config/ghostty/themes/solarized-dark"
"ghostty/themes/solarized-light" = "/Users/williamnapier/.config/ghostty/themes/solarized-light"
"git/gitconfig" = "/Users/williamnapier/.gitconfig"
"helix/config.toml" = "/Users/williamnapier/.config/helix/config.toml"
"karabiner/.DS_Store" = "/Users/williamnapier/.config/karabiner/.DS_Store"
"karabiner/assets/complex_modifications/1690652878.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/1690652878.json"
"karabiner/assets/complex_modifications/1690668710.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/1690668710.json"
"karabiner/assets/complex_modifications/Map physical left_shift key to ` and ~.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/Map physical left_shift key to ` and ~.json"
"karabiner/assets/complex_modifications/MouseKeysMod" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/MouseKeysMod"
"karabiner/automatic_backups/karabiner_20240703.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240703.json"
"karabiner/automatic_backups/karabiner_20240704.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240704.json"
"karabiner/automatic_backups/karabiner_20240727.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240727.json"
"karabiner/automatic_backups/karabiner_20240821.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240821.json"
"karabiner/automatic_backups/karabiner_20240902.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240902.json"
"karabiner/automatic_backups/karabiner_20240912.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240912.json"
"karabiner/automatic_backups/karabiner_20241107.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20241107.json"
"karabiner/automatic_backups/karabiner_20250326.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250326.json"
"karabiner/automatic_backups/karabiner_20250327.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250327.json"
"karabiner/automatic_backups/karabiner_20250519.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250519.json"
"karabiner/automatic_backups/karabiner_20250520.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250520.json"
"karabiner/automatic_backups/karabiner_20250521.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250521.json"
"karabiner/automatic_backups/karabiner_20250530.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250530.json"
"karabiner/automatic_backups/karabiner_20250531.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250531.json"
"karabiner/automatic_backups/karabiner_20250612.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250612.json"
"karabiner/automatic_backups/karabiner_20250614.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250614.json"
"karabiner/automatic_backups/karabiner_20250617.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250617.json"
"karabiner/automatic_backups/karabiner_20250707.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250707.json"
"karabiner/automatic_backups/karabiner_20250713.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250713.json"
"karabiner/automatic_backups/karabiner_20250811.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250811.json"
"karabiner/backups/miryoku-setup-20250811-223541/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-223541/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-223633/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-223633/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225243/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225243/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225728/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225728/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225900/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225900/karabiner-backup.json"
"karabiner/karabiner.json" = "/Users/williamnapier/.config/karabiner/karabiner.json"
"nushell/config.nu" = "/Users/williamnapier/.config/nushell/config.nu"
"nushell/env.nu" = "/Users/williamnapier/.config/nushell/env.nu"
"nvim/.DS_Store" = "/Users/williamnapier/.config/nvim/.DS_Store"
"nvim/.github/ISSUE_TEMPLATE/bug_report.md" = "/Users/williamnapier/.config/nvim/.github/ISSUE_TEMPLATE/bug_report.md"
"nvim/.github/pull_request_template.md" = "/Users/williamnapier/.config/nvim/.github/pull_request_template.md"
"nvim/.github/workflows/stylua.yml" = "/Users/williamnapier/.config/nvim/.github/workflows/stylua.yml"
"nvim/.gitignore" = "/Users/williamnapier/.config/nvim/.gitignore"
"nvim/.stylua.toml" = "/Users/williamnapier/.config/nvim/.stylua.toml"
"nvim/LICENSE.md" = "/Users/williamnapier/.config/nvim/LICENSE.md"
"nvim/README.md" = "/Users/williamnapier/.config/nvim/README.md"
"nvim/doc/kickstart.txt" = "/Users/williamnapier/.config/nvim/doc/kickstart.txt"
"nvim/doc/tags" = "/Users/williamnapier/.config/nvim/doc/tags"
"nvim/init.lua" = "/Users/williamnapier/.config/nvim/init.lua"
"nvim/init.lua.backup-20250811-185641" = "/Users/williamnapier/.config/nvim/init.lua.backup-20250811-185641"
"nvim/last_session.vim" = "/Users/williamnapier/.config/nvim/last_session.vim"
"nvim/lazy-lock.json" = "/Users/williamnapier/.config/nvim/lazy-lock.json"
"nvim/lua/custom/.DS_Store" = "/Users/williamnapier/.config/nvim/lua/custom/.DS_Store"
"nvim/lua/custom/plugins/init.lua" = "/Users/williamnapier/.config/nvim/lua/custom/plugins/init.lua"
"nvim/lua/debug_telescope.lua" = "/Users/williamnapier/.config/nvim/lua/debug_telescope.lua"
"nvim/lua/ghostty-yazi.lua" = "/Users/williamnapier/.config/nvim/lua/ghostty-yazi.lua"
"nvim/lua/health/kickstart.lua" = "/Users/williamnapier/.config/nvim/lua/health/kickstart.lua"
"nvim/lua/kickstart.nvim/plugins/autopairs.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/autopairs.lua"
"nvim/lua/kickstart.nvim/plugins/debug.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/debug.lua"
"nvim/lua/kickstart.nvim/plugins/gitsigns.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/gitsigns.lua"
"nvim/lua/kickstart.nvim/plugins/indent_line.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/indent_line.lua"
"nvim/lua/kickstart.nvim/plugins/lint.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/lint.lua"
"nvim/lua/kickstart.nvim/plugins/neo-tree.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/neo-tree.lua"
"nvim/lua/plugins/anki.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/anki.lua"
"nvim/lua/plugins/auto-save.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/auto-save.lua"
"nvim/lua/plugins/link-validator.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/link-validator.lua"
"nvim/lua/plugins/prose.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/prose.lua"
"nvim/lua/plugins/telekasten.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua"
"nvim/lua/plugins/telekasten.lua.backup-20250811-185650" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua.backup-20250811-185650"
"nvim/lua/plugins/yazi.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/yazi.lua"
"nvim/lua/telescope_filter_debug.lua" = "/Users/williamnapier/.config/nvim/lua/telescope_filter_debug.lua"
"nvim/spell/en.utf-8.add" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add"
"nvim/spell/en.utf-8.add.spl" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add.spl"
"nvim/telescope_debug.lua" = "/Users/williamnapier/.config/nvim/telescope_debug.lua"
"scripts/daily-note" = "/Users/williamnapier/.local/bin/daily-note"
"scripts/daypage-template" = "/Users/williamnapier/.local/bin/daypage-template"
"scripts/hx-open-system-cross" = "/Users/williamnapier/.local/bin/hx-open-system-cross"
"scripts/hx-smart-gf-cross" = "/Users/williamnapier/.local/bin/hx-smart-gf-cross"
"scripts/hx-wiki" = "/Users/williamnapier/.local/bin/hx-wiki"
"scripts/obsidian-linker.sh" = "/Users/williamnapier/.local/bin/obsidian-linker.sh"
"scripts/zellij-sync.nu" = "/Users/williamnapier/.local/bin/zellij-sync.nu"
"shell/zshrc" = "/Users/williamnapier/.zshrc"
"sketchybar/colors.sh" = "/Users/williamnapier/.config/sketchybar/colors.sh"
"sketchybar/items/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/items/aerospace.sh"
"sketchybar/items/battery.sh" = "/Users/williamnapier/.config/sketchybar/items/battery.sh"
"sketchybar/items/calendar.sh" = "/Users/williamnapier/.config/sketchybar/items/calendar.sh"
"sketchybar/items/clock.sh" = "/Users/williamnapier/.config/sketchybar/items/clock.sh"
"sketchybar/items/cpu.sh" = "/Users/williamnapier/.config/sketchybar/items/cpu.sh"
"sketchybar/items/front_app.sh" = "/Users/williamnapier/.config/sketchybar/items/front_app.sh"
"sketchybar/items/spaces.sh" = "/Users/williamnapier/.config/sketchybar/items/spaces.sh"
"sketchybar/items/volume.sh" = "/Users/williamnapier/.config/sketchybar/items/volume.sh"
"sketchybar/plugins/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace.sh"
"sketchybar/plugins/aerospace_windows.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace_windows.sh"
"sketchybar/plugins/aerospace_workspace_tracker.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace_workspace_tracker.sh"
"sketchybar/plugins/battery.sh" = "/Users/williamnapier/.config/sketchybar/plugins/battery.sh"
"sketchybar/plugins/calendar.sh" = "/Users/williamnapier/.config/sketchybar/plugins/calendar.sh"
"sketchybar/plugins/clock.sh" = "/Users/williamnapier/.config/sketchybar/plugins/clock.sh"
"sketchybar/plugins/cpu.sh" = "/Users/williamnapier/.config/sketchybar/plugins/cpu.sh"
"sketchybar/plugins/front_app.sh" = "/Users/williamnapier/.config/sketchybar/plugins/front_app.sh"
"sketchybar/plugins/icon_map_fn.sh" = "/Users/williamnapier/.config/sketchybar/plugins/icon_map_fn.sh"
"sketchybar/plugins/volume.sh" = "/Users/williamnapier/.config/sketchybar/plugins/volume.sh"
"sketchybar/sketchybarrc" = "/Users/williamnapier/.config/sketchybar/sketchybarrc"
"wezterm/wezterm.lua" = "/Users/williamnapier/.config/wezterm/wezterm.lua"
"yazi/keymap.toml" = "/Users/williamnapier/.config/yazi/keymap.toml"
"yazi/yazi.toml" = "/Users/williamnapier/.config/yazi/yazi.toml"
"zellij/config.kdl" = "/Users/williamnapier/.config/zellij/config.kdl"

[templates]
