[symlinks]
"aerospace/aerospace.toml" = "/Users/williamnapier/.config/aerospace/aerospace.toml"
"ghostty/config" = "/Users/williamnapier/Library/Application Support/com.mitchellh.ghostty/config"
"ghostty/themes/solarized-dark" = "/Users/williamnapier/.config/ghostty/themes/solarized-dark"
"ghostty/themes/solarized-light" = "/Users/williamnapier/.config/ghostty/themes/solarized-light"
"git/gitconfig" = "/Users/williamnapier/.gitconfig"
"helix/config.toml" = "/Users/williamnapier/.config/helix/config.toml"
"helix/themes/solarized_dark_modal.toml" = "/Users/williamnapier/.config/helix/themes/solarized_dark_modal.toml"
"helix/themes/solarized_dark_modal_wiki.toml" = "/Users/williamnapier/.config/helix/themes/solarized_dark_modal_wiki.toml"
"helix/themes/solarized_light_modal.toml" = "/Users/williamnapier/.config/helix/themes/solarized_light_modal.toml"
"helix/themes/test_theme.toml" = "/Users/williamnapier/.config/helix/themes/test_theme.toml"
"karabiner/karabiner.json" = "/Users/williamnapier/.config/karabiner/karabiner.json"
"nushell/config.nu" = "/Users/williamnapier/.config/nushell/config.nu"
"nushell/env.nu" = "/Users/williamnapier/.config/nushell/env.nu"
"nushell/scripts/quantified-tracking-v2.nu" = "/Users/williamnapier/.config/nushell/scripts/quantified-tracking-v2.nu"
"nushell/scripts/quantified-tracking.nu" = "/Users/williamnapier/.config/nushell/scripts/quantified-tracking.nu"
"nvim/doc/kickstart.txt" = "/Users/williamnapier/.config/nvim/doc/kickstart.txt"
"nvim/doc/tags" = "/Users/williamnapier/.config/nvim/doc/tags"
"nvim/init.lua" = "/Users/williamnapier/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "/Users/williamnapier/.config/nvim/lazy-lock.json"
"nvim/lua/custom/.DS_Store" = "/Users/williamnapier/.config/nvim/lua/custom/.DS_Store"
"nvim/lua/custom/plugins/init.lua" = "/Users/williamnapier/.config/nvim/lua/custom/plugins/init.lua"
"nvim/lua/debug_telescope.lua" = "/Users/williamnapier/.config/nvim/lua/debug_telescope.lua"
"nvim/lua/ghostty-yazi.lua" = "/Users/williamnapier/.config/nvim/lua/ghostty-yazi.lua"
"nvim/lua/health/kickstart.lua" = "/Users/williamnapier/.config/nvim/lua/health/kickstart.lua"
"nvim/lua/kickstart.nvim/plugins/autopairs.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/autopairs.lua"
"nvim/lua/kickstart.nvim/plugins/debug.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/debug.lua"
"nvim/lua/kickstart.nvim/plugins/gitsigns.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/gitsigns.lua"
"nvim/lua/kickstart.nvim/plugins/indent_line.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/indent_line.lua"
"nvim/lua/kickstart.nvim/plugins/lint.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/lint.lua"
"nvim/lua/kickstart.nvim/plugins/neo-tree.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/neo-tree.lua"
"nvim/lua/plugins/anki.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/anki.lua"
"nvim/lua/plugins/auto-save.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/auto-save.lua"
"nvim/lua/plugins/link-validator.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/link-validator.lua"
"nvim/lua/plugins/prose.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/prose.lua"
"nvim/lua/plugins/telekasten.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua"
"nvim/lua/plugins/telekasten.lua.backup-20250811-185650" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua.backup-20250811-185650"
"nvim/lua/plugins/yazi.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/yazi.lua"
"nvim/lua/telescope_filter_debug.lua" = "/Users/williamnapier/.config/nvim/lua/telescope_filter_debug.lua"
"nvim/spell/en.utf-8.add" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add"
"nvim/spell/en.utf-8.add.spl" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add.spl"
"scripts/activity-duration-processor" = "/Users/williamnapier/.local/bin/activity-duration-processor"
"scripts/activity-duration-processor-buffer" = "/Users/williamnapier/.local/bin/activity-duration-processor-buffer"
"scripts/activity-watcher-renu" = "/Users/williamnapier/.local/bin/activity-watcher-renu"
"scripts/citation-picker-cross-platform.sh" = "/Users/williamnapier/.local/bin/citation-picker-cross-platform.sh"
"scripts/citation-picker.sh" = "/Users/williamnapier/.local/bin/citation-picker.sh"
"scripts/citation-watcher-renu" = "/Users/williamnapier/.local/bin/citation-watcher-renu"
"scripts/claude-docs-backup" = "/Users/williamnapier/.local/bin/claude-docs-backup"
"scripts/claude-docs-watcher-renu" = "/Users/williamnapier/.local/bin/claude-docs-watcher-renu"
"scripts/cross-platform-paths" = "/Users/williamnapier/.local/bin/cross-platform-paths"
"scripts/daily-note.nu" = "/Users/williamnapier/.local/bin/daily-note.nu"
"scripts/daypage-template" = "/Users/williamnapier/.local/bin/daypage-template"
"scripts/deploy-semantic-search" = "/Users/williamnapier/.local/bin/deploy-semantic-search"
"scripts/detect-platform" = "/Users/williamnapier/.local/bin/detect-platform"
"scripts/dotter-add" = "/Users/williamnapier/.local/bin/dotter-add"
"scripts/dotter-audit" = "/Users/williamnapier/.local/bin/dotter-audit"
"scripts/dotter-auto-onboard" = "/Users/williamnapier/.local/bin/dotter-auto-onboard"
"scripts/dotter-auto-onboard-simple" = "/Users/williamnapier/.local/bin/dotter-auto-onboard-simple"
"scripts/dotter-complete-audit" = "/Users/williamnapier/.local/bin/dotter-complete-audit"
"scripts/dotter-drift-cron" = "/Users/williamnapier/.local/bin/dotter-drift-cron"
"scripts/dotter-drift-monitor" = "/Users/williamnapier/.local/bin/dotter-drift-monitor"
"scripts/dotter-drift-watcher-renu" = "/Users/williamnapier/.local/bin/dotter-drift-watcher-renu"
"scripts/dotter-enforce-compliance" = "/Users/williamnapier/.local/bin/dotter-enforce-compliance"
"scripts/dotter-orphan-detector" = "/Users/williamnapier/.local/bin/dotter-orphan-detector"
"scripts/dotter-orphan-detector-v2" = "/Users/williamnapier/.local/bin/dotter-orphan-detector-v2"
"scripts/dotter-protect-all" = "/Users/williamnapier/.local/bin/dotter-protect-all"
"scripts/dotter-protect-all-cross-platform" = "/Users/williamnapier/.local/bin/dotter-protect-all-cross-platform"
"scripts/dotter-realtime-watcher-renu" = "/Users/williamnapier/.local/bin/dotter-realtime-watcher-renu"
"scripts/dotter-verify-protection" = "/Users/williamnapier/.local/bin/dotter-verify-protection"
"scripts/dotter-verify-protection-cross-platform" = "/Users/williamnapier/.local/bin/dotter-verify-protection-cross-platform"
"scripts/drift-status" = "/Users/williamnapier/.local/bin/drift-status"
"scripts/fix-corrupted-dates" = "/Users/williamnapier/.local/bin/fix-corrupted-dates"
"scripts/fix-date-corruption-emergency" = "/Users/williamnapier/.local/bin/fix-date-corruption-emergency"
"scripts/forge-linker.nu" = "/Users/williamnapier/.local/bin/forge-linker.nu"
"scripts/get-openai-key" = "/Users/williamnapier/.local/bin/get-openai-key"
"scripts/helix-activity-watcher-renu" = "/Users/williamnapier/.local/bin/helix-activity-watcher-renu"
"scripts/hx-auto" = "/Users/williamnapier/.local/bin/hx-auto"
"scripts/hx-insert-date" = "/Users/williamnapier/.local/bin/hx-insert-date"
"scripts/hx-insert-datetime" = "/Users/williamnapier/.local/bin/hx-insert-datetime"
"scripts/hx-insert-time" = "/Users/williamnapier/.local/bin/hx-insert-time"
"scripts/hx-mark-revisit" = "/Users/williamnapier/.local/bin/hx-mark-revisit"
"scripts/hx-process-durations-wezterm" = "/Users/williamnapier/.local/bin/hx-process-durations-wezterm"
"scripts/hx-wiki" = "/Users/williamnapier/.local/bin/hx-wiki"
"scripts/new-script" = "/Users/williamnapier/.local/bin/new-script"
"scripts/obsidian-content-search-interactive.sh" = "/Users/williamnapier/.local/bin/obsidian-content-search-interactive.sh"
"scripts/obsidian-linker-cross-platform.sh" = "/Users/williamnapier/.local/bin/obsidian-linker-cross-platform.sh"
"scripts/obsidian-linker.sh" = "/Users/williamnapier/.local/bin/obsidian-linker.sh"
"scripts/obsidian-semantic-search.sh" = "/Users/williamnapier/.local/bin/obsidian-semantic-search.sh"
"scripts/process-count.nu" = "/Users/williamnapier/.local/bin/process-count.nu"
"scripts/rotate-linkmanager-logs" = "/Users/williamnapier/.local/bin/rotate-linkmanager-logs"
"scripts/script-ready-deploy" = "/Users/williamnapier/.local/bin/script-ready-deploy"
"scripts/search-comparison-test" = "/Users/williamnapier/.local/bin/search-comparison-test"
"scripts/semantic-auto-update" = "/Users/williamnapier/.local/bin/semantic-auto-update"
"scripts/semantic-indexer" = "/Users/williamnapier/.local/bin/semantic-indexer"
"scripts/semantic-query" = "/Users/williamnapier/.local/bin/semantic-query"
"scripts/setup-drift-monitoring" = "/Users/williamnapier/.local/bin/setup-drift-monitoring"
"scripts/setup-realtime-onboarding" = "/Users/williamnapier/.local/bin/setup-realtime-onboarding"
"scripts/setup-zellij-zombie-prevention-cross-platform" = "/Users/williamnapier/.local/bin/setup-zellij-zombie-prevention-cross-platform"
"scripts/simple-file-preview" = "/Users/williamnapier/.local/bin/simple-file-preview"
"scripts/test-skim-floating" = "/Users/williamnapier/.local/bin/test-skim-floating"
"scripts/word-wrap-preview.nu" = "/Users/williamnapier/.local/bin/word-wrap-preview.nu"
"scripts/yazi-project-file-search-floating" = "/Users/williamnapier/.local/bin/yazi-project-file-search-floating"
"scripts/yazi-project-file-search-floating.nu" = "/Users/williamnapier/.local/bin/yazi-project-file-search-floating.nu"
"scripts/yazi-recent-files.nu" = "/Users/williamnapier/.local/bin/yazi-recent-files.nu"
"scripts/yazi-search-with-preview" = "/Users/williamnapier/.local/bin/yazi-search-with-preview"
"scripts/zellij-cleanup.nu" = "/Users/williamnapier/.local/bin/zellij-cleanup.nu"
"scripts/zellij-zombie-killer" = "/Users/williamnapier/.local/bin/zellij-zombie-killer"
"scripts/zellij-zombie-watcher-renu" = "/Users/williamnapier/.local/bin/zellij-zombie-watcher-renu"
"scripts/zj" = "/Users/williamnapier/.local/bin/zj"
"scripts/zotero-bridge-renu" = "/Users/williamnapier/.local/bin/zotero-bridge-renu"
"scripts/zotero-pdf-watcher-renu" = "/Users/williamnapier/.local/bin/zotero-pdf-watcher-renu"
"shell/zshrc" = "/Users/williamnapier/.zshrc"
"sketchybar/colors.sh" = "/Users/williamnapier/.config/sketchybar/colors.sh"
"sketchybar/items/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/items/aerospace.sh"
"sketchybar/items/battery.sh" = "/Users/williamnapier/.config/sketchybar/items/battery.sh"
"sketchybar/items/calendar.sh" = "/Users/williamnapier/.config/sketchybar/items/calendar.sh"
"sketchybar/items/clock.sh" = "/Users/williamnapier/.config/sketchybar/items/clock.sh"
"sketchybar/plugins/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace.sh"
"sketchybar/plugins/battery.sh" = "/Users/williamnapier/.config/sketchybar/plugins/battery.sh"
"sketchybar/plugins/calendar.sh" = "/Users/williamnapier/.config/sketchybar/plugins/calendar.sh"
"sketchybar/plugins/clock.sh" = "/Users/williamnapier/.config/sketchybar/plugins/clock.sh"
"sketchybar/sketchybarrc" = "/Users/williamnapier/.config/sketchybar/sketchybarrc"
"starship.toml" = "/Users/williamnapier/.config/starship.toml"
"wezterm/wezterm.lua" = "/Users/williamnapier/.config/wezterm/wezterm.lua"
"yazi/flavors/dracula.yazi/LICENSE" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/LICENSE"
"yazi/flavors/dracula.yazi/LICENSE-tmtheme" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/LICENSE-tmtheme"
"yazi/flavors/dracula.yazi/README.md" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/README.md"
"yazi/flavors/dracula.yazi/flavor.toml" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/flavor.toml"
"yazi/flavors/dracula.yazi/preview.png" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/preview.png"
"yazi/flavors/dracula.yazi/tmtheme.xml" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/tmtheme.xml"
"yazi/flavors/solarized-dark.yazi/flavor.toml" = "/Users/williamnapier/.config/yazi/flavors/solarized-dark.yazi/flavor.toml"
"yazi/flavors/solarized-light.yazi/flavor.toml" = "/Users/williamnapier/.config/yazi/flavors/solarized-light.yazi/flavor.toml"
"yazi/keymap.toml" = "/Users/williamnapier/.config/yazi/keymap.toml"
"yazi/theme.toml" = "/Users/williamnapier/.config/yazi/theme.toml"
"yazi/yazi.toml" = "/Users/williamnapier/.config/yazi/yazi.toml"
"zellij/config.kdl" = "/Users/williamnapier/.config/zellij/config.kdl"
"zellij/layouts/desktop-27-simple.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop-27-simple.kdl"
"zellij/layouts/desktop-27.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop-27.kdl"
"zellij/layouts/desktop-quarters.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop-quarters.kdl"
"zellij/layouts/desktop.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop.kdl"
"zellij/layouts/laptop.kdl" = "/Users/williamnapier/.config/zellij/layouts/laptop.kdl"
"zellij/layouts/minimal-test.kdl" = "/Users/williamnapier/.config/zellij/layouts/minimal-test.kdl"
"zellij/layouts/test-basic.kdl" = "/Users/williamnapier/.config/zellij/layouts/test-basic.kdl"

[templates]
