[symlinks]
"aerospace/aerospace.toml" = "/Users/williamnapier/.config/aerospace/aerospace.toml"
"ghostty/config" = "/Users/williamnapier/Library/Application Support/com.mitchellh.ghostty/config"
"ghostty/themes/solarized-dark" = "/Users/williamnapier/.config/ghostty/themes/solarized-dark"
"ghostty/themes/solarized-light" = "/Users/williamnapier/.config/ghostty/themes/solarized-light"
"git/gitconfig" = "/Users/williamnapier/.gitconfig"
"helix/config.toml" = "/Users/williamnapier/.config/helix/config.toml"
"helix/themes/solarized_dark_modal.toml" = "/Users/williamnapier/.config/helix/themes/solarized_dark_modal.toml"
"helix/themes/solarized_dark_modal_wiki.toml" = "/Users/williamnapier/.config/helix/themes/solarized_dark_modal_wiki.toml"
"helix/themes/solarized_light_modal.toml" = "/Users/williamnapier/.config/helix/themes/solarized_light_modal.toml"
"helix/themes/test_theme.toml" = "/Users/williamnapier/.config/helix/themes/test_theme.toml"
"karabiner/.DS_Store" = "/Users/williamnapier/.config/karabiner/.DS_Store"
"karabiner/assets/complex_modifications/1690652878.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/1690652878.json"
"karabiner/assets/complex_modifications/1690668710.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/1690668710.json"
"karabiner/assets/complex_modifications/Map physical left_shift key to ` and ~.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/Map physical left_shift key to ` and ~.json"
"karabiner/assets/complex_modifications/MouseKeysMod" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/MouseKeysMod"
"karabiner/assets/complex_modifications/left-control-backtick-tilde.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/left-control-backtick-tilde.json"
"karabiner/assets/complex_modifications/left-shift-to-backtick-tilde.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/left-shift-to-backtick-tilde.json"
"karabiner/assets/complex_modifications/right-control-backtick-tilde.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/right-control-backtick-tilde.json"
"karabiner/assets/complex_modifications/right-control-hybrid-backtick.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/right-control-hybrid-backtick.json"
"karabiner/assets/complex_modifications/right-control-normal-backtick.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/right-control-normal-backtick.json"
"karabiner/assets/complex_modifications/right-control-passthrough-fix.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/right-control-passthrough-fix.json"
"karabiner/assets/complex_modifications/right-control-real-backtick.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/right-control-real-backtick.json"
"karabiner/assets/complex_modifications/right-control-smart-backtick.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/right-control-smart-backtick.json"
"karabiner/assets/complex_modifications/section-key-cmd-backtick-alt.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/section-key-cmd-backtick-alt.json"
"karabiner/assets/complex_modifications/section-key-delayed-cmd.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/section-key-delayed-cmd.json"
"karabiner/assets/complex_modifications/section-key-window-cycling.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/section-key-window-cycling.json"
"karabiner/automatic_backups/karabiner_20240703.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240703.json"
"karabiner/automatic_backups/karabiner_20240704.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240704.json"
"karabiner/automatic_backups/karabiner_20240727.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240727.json"
"karabiner/automatic_backups/karabiner_20240821.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240821.json"
"karabiner/automatic_backups/karabiner_20240902.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240902.json"
"karabiner/automatic_backups/karabiner_20240912.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240912.json"
"karabiner/automatic_backups/karabiner_20241107.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20241107.json"
"karabiner/automatic_backups/karabiner_20250326.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250326.json"
"karabiner/automatic_backups/karabiner_20250327.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250327.json"
"karabiner/automatic_backups/karabiner_20250519.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250519.json"
"karabiner/automatic_backups/karabiner_20250520.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250520.json"
"karabiner/automatic_backups/karabiner_20250521.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250521.json"
"karabiner/automatic_backups/karabiner_20250530.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250530.json"
"karabiner/automatic_backups/karabiner_20250531.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250531.json"
"karabiner/automatic_backups/karabiner_20250612.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250612.json"
"karabiner/automatic_backups/karabiner_20250614.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250614.json"
"karabiner/automatic_backups/karabiner_20250617.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250617.json"
"karabiner/automatic_backups/karabiner_20250707.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250707.json"
"karabiner/automatic_backups/karabiner_20250713.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250713.json"
"karabiner/automatic_backups/karabiner_20250811.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250811.json"
"karabiner/automatic_backups/karabiner_20250813.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250813.json"
"karabiner/automatic_backups/karabiner_20250819.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250819.json"
"karabiner/backups/miryoku-setup-20250811-223541/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-223541/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-223633/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-223633/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225243/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225243/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225728/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225728/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225900/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225900/karabiner-backup.json"
"karabiner/karabiner.json" = "/Users/williamnapier/.config/karabiner/karabiner.json"
"nushell/config.nu" = "/Users/williamnapier/.config/nushell/config.nu"
"nushell/env.nu" = "/Users/williamnapier/.config/nushell/env.nu"
"nvim/doc/kickstart.txt" = "/Users/williamnapier/.config/nvim/doc/kickstart.txt"
"nvim/doc/tags" = "/Users/williamnapier/.config/nvim/doc/tags"
"nvim/init.lua" = "/Users/williamnapier/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "/Users/williamnapier/.config/nvim/lazy-lock.json"
"nvim/lua/custom/.DS_Store" = "/Users/williamnapier/.config/nvim/lua/custom/.DS_Store"
"nvim/lua/custom/plugins/init.lua" = "/Users/williamnapier/.config/nvim/lua/custom/plugins/init.lua"
"nvim/lua/debug_telescope.lua" = "/Users/williamnapier/.config/nvim/lua/debug_telescope.lua"
"nvim/lua/ghostty-yazi.lua" = "/Users/williamnapier/.config/nvim/lua/ghostty-yazi.lua"
"nvim/lua/health/kickstart.lua" = "/Users/williamnapier/.config/nvim/lua/health/kickstart.lua"
"nvim/lua/kickstart.nvim/plugins/autopairs.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/autopairs.lua"
"nvim/lua/kickstart.nvim/plugins/debug.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/debug.lua"
"nvim/lua/kickstart.nvim/plugins/gitsigns.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/gitsigns.lua"
"nvim/lua/kickstart.nvim/plugins/indent_line.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/indent_line.lua"
"nvim/lua/kickstart.nvim/plugins/lint.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/lint.lua"
"nvim/lua/kickstart.nvim/plugins/neo-tree.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/neo-tree.lua"
"nvim/lua/plugins/anki.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/anki.lua"
"nvim/lua/plugins/auto-save.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/auto-save.lua"
"nvim/lua/plugins/link-validator.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/link-validator.lua"
"nvim/lua/plugins/prose.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/prose.lua"
"nvim/lua/plugins/telekasten.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua"
"nvim/lua/plugins/telekasten.lua.backup-20250811-185650" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua.backup-20250811-185650"
"nvim/lua/plugins/yazi.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/yazi.lua"
"nvim/lua/telescope_filter_debug.lua" = "/Users/williamnapier/.config/nvim/lua/telescope_filter_debug.lua"
"nvim/spell/en.utf-8.add" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add"
"nvim/spell/en.utf-8.add.spl" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add.spl"
"scripts/citation-picker.sh" = "/Users/williamnapier/.local/bin/citation-picker.sh"
"scripts/claude" = "/Users/williamnapier/.local/bin/claude"
"scripts/daily-note" = "/Users/williamnapier/.local/bin/daily-note"
"scripts/daypage-template" = "/Users/williamnapier/.local/bin/daypage-template"
"scripts/dotter-add" = "/Users/williamnapier/.local/bin/dotter-add"
"scripts/dotter-audit" = "/Users/williamnapier/.local/bin/dotter-audit"
"scripts/dotter-protect-all" = "/Users/williamnapier/.local/bin/dotter-protect-all"
"scripts/dotter-protect-all-cross-platform" = "/Users/williamnapier/.local/bin/dotter-protect-all-cross-platform"
"scripts/dotter-verify-protection" = "/Users/williamnapier/.local/bin/dotter-verify-protection"
"scripts/dotter-verify-protection-cross-platform" = "/Users/williamnapier/.local/bin/dotter-verify-protection-cross-platform"
"scripts/hx-auto" = "/Users/williamnapier/.local/bin/hx-auto"
"scripts/hx-insert-date" = "/Users/williamnapier/.local/bin/hx-insert-date"
"scripts/hx-insert-datetime" = "/Users/williamnapier/.local/bin/hx-insert-datetime"
"scripts/hx-insert-time" = "/Users/williamnapier/.local/bin/hx-insert-time"
"scripts/hx-wiki" = "/Users/williamnapier/.local/bin/hx-wiki"
"scripts/obsidian-linker.sh" = "/Users/williamnapier/.local/bin/obsidian-linker.sh"
"scripts/search-comparison-test" = "/Users/williamnapier/.local/bin/search-comparison-test"
"scripts/semantic-indexer" = "/Users/williamnapier/.local/bin/semantic-indexer"
"scripts/semantic-query" = "/Users/williamnapier/.local/bin/semantic-query"
"scripts/zj" = "/Users/williamnapier/.local/bin/zj"
"shell/zshrc" = "/Users/williamnapier/.zshrc"
"sketchybar/colors.sh" = "/Users/williamnapier/.config/sketchybar/colors.sh"
"sketchybar/items/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/items/aerospace.sh"
"sketchybar/items/battery.sh" = "/Users/williamnapier/.config/sketchybar/items/battery.sh"
"sketchybar/items/calendar.sh" = "/Users/williamnapier/.config/sketchybar/items/calendar.sh"
"sketchybar/items/clock.sh" = "/Users/williamnapier/.config/sketchybar/items/clock.sh"
"sketchybar/items/cpu.sh" = "/Users/williamnapier/.config/sketchybar/items/cpu.sh"
"sketchybar/items/front_app.sh" = "/Users/williamnapier/.config/sketchybar/items/front_app.sh"
"sketchybar/items/spaces.sh" = "/Users/williamnapier/.config/sketchybar/items/spaces.sh"
"sketchybar/items/volume.sh" = "/Users/williamnapier/.config/sketchybar/items/volume.sh"
"sketchybar/plugins/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace.sh"
"sketchybar/plugins/aerospace_windows.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace_windows.sh"
"sketchybar/plugins/aerospace_workspace_tracker.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace_workspace_tracker.sh"
"sketchybar/plugins/battery.sh" = "/Users/williamnapier/.config/sketchybar/plugins/battery.sh"
"sketchybar/plugins/calendar.sh" = "/Users/williamnapier/.config/sketchybar/plugins/calendar.sh"
"sketchybar/plugins/clock.sh" = "/Users/williamnapier/.config/sketchybar/plugins/clock.sh"
"sketchybar/plugins/cpu.sh" = "/Users/williamnapier/.config/sketchybar/plugins/cpu.sh"
"sketchybar/plugins/front_app.sh" = "/Users/williamnapier/.config/sketchybar/plugins/front_app.sh"
"sketchybar/plugins/icon_map_fn.sh" = "/Users/williamnapier/.config/sketchybar/plugins/icon_map_fn.sh"
"sketchybar/plugins/volume.sh" = "/Users/williamnapier/.config/sketchybar/plugins/volume.sh"
"sketchybar/sketchybarrc" = "/Users/williamnapier/.config/sketchybar/sketchybarrc"
"starship.toml" = "/Users/williamnapier/.config/starship.toml"
"wezterm/wezterm.lua" = "/Users/williamnapier/.config/wezterm/wezterm.lua"
"yazi/flavors/dracula.yazi/LICENSE" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/LICENSE"
"yazi/flavors/dracula.yazi/LICENSE-tmtheme" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/LICENSE-tmtheme"
"yazi/flavors/dracula.yazi/README.md" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/README.md"
"yazi/flavors/dracula.yazi/flavor.toml" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/flavor.toml"
"yazi/flavors/dracula.yazi/preview.png" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/preview.png"
"yazi/flavors/dracula.yazi/tmtheme.xml" = "/Users/williamnapier/.config/yazi/flavors/dracula.yazi/tmtheme.xml"
"yazi/flavors/solarized-dark.yazi/flavor.toml" = "/Users/williamnapier/.config/yazi/flavors/solarized-dark.yazi/flavor.toml"
"yazi/flavors/solarized-light.yazi/flavor.toml" = "/Users/williamnapier/.config/yazi/flavors/solarized-light.yazi/flavor.toml"
"yazi/keymap.toml" = "/Users/williamnapier/.config/yazi/keymap.toml"
"yazi/plugins/archive.lua" = "/Users/williamnapier/.config/yazi/plugins/archive.lua"
"yazi/plugins/code.lua" = "/Users/williamnapier/.config/yazi/plugins/code.lua"
"yazi/plugins/dds.lua" = "/Users/williamnapier/.config/yazi/plugins/dds.lua"
"yazi/plugins/empty.lua" = "/Users/williamnapier/.config/yazi/plugins/empty.lua"
"yazi/plugins/extract.lua" = "/Users/williamnapier/.config/yazi/plugins/extract.lua"
"yazi/plugins/file.lua" = "/Users/williamnapier/.config/yazi/plugins/file.lua"
"yazi/plugins/folder.lua" = "/Users/williamnapier/.config/yazi/plugins/folder.lua"
"yazi/plugins/font.lua" = "/Users/williamnapier/.config/yazi/plugins/font.lua"
"yazi/plugins/git.yazi/LICENSE" = "/Users/williamnapier/.config/yazi/plugins/git.yazi/LICENSE"
"yazi/plugins/git.yazi/README.md" = "/Users/williamnapier/.config/yazi/plugins/git.yazi/README.md"
"yazi/plugins/git.yazi/main.lua" = "/Users/williamnapier/.config/yazi/plugins/git.yazi/main.lua"
"yazi/plugins/image.lua" = "/Users/williamnapier/.config/yazi/plugins/image.lua"
"yazi/plugins/json.lua" = "/Users/williamnapier/.config/yazi/plugins/json.lua"
"yazi/plugins/magick.lua" = "/Users/williamnapier/.config/yazi/plugins/magick.lua"
"yazi/plugins/mime.lua" = "/Users/williamnapier/.config/yazi/plugins/mime.lua"
"yazi/plugins/noop.lua" = "/Users/williamnapier/.config/yazi/plugins/noop.lua"
"yazi/plugins/nushell-preview.lua" = "/Users/williamnapier/.config/yazi/plugins/nushell-preview.lua"
"yazi/plugins/pdf.lua" = "/Users/williamnapier/.config/yazi/plugins/pdf.lua"
"yazi/plugins/session.lua" = "/Users/williamnapier/.config/yazi/plugins/session.lua"
"yazi/plugins/skim.lua" = "/Users/williamnapier/.config/yazi/plugins/skim.lua"
"yazi/plugins/svg.lua" = "/Users/williamnapier/.config/yazi/plugins/svg.lua"
"yazi/plugins/video.lua" = "/Users/williamnapier/.config/yazi/plugins/video.lua"
"yazi/plugins/zotero-import.lua" = "/Users/williamnapier/.config/yazi/plugins/zotero-import.lua"
"yazi/plugins/zotero.yazi/init.lua" = "/Users/williamnapier/.config/yazi/plugins/zotero.yazi/init.lua"
"yazi/scripts/dir-preview-simple.sh" = "/Users/williamnapier/.config/yazi/scripts/dir-preview-simple.sh"
"yazi/scripts/dir-preview.nu" = "/Users/williamnapier/.config/yazi/scripts/dir-preview.nu"
"yazi/scripts/file-preview.nu" = "/Users/williamnapier/.config/yazi/scripts/file-preview.nu"
"yazi/scripts/obsidian-preview.nu" = "/Users/williamnapier/.config/yazi/scripts/obsidian-preview.nu"
"yazi/scripts/search-preview.nu" = "/Users/williamnapier/.config/yazi/scripts/search-preview.nu"
"yazi/theme.toml" = "/Users/williamnapier/.config/yazi/theme.toml"
"yazi/yazi.toml" = "/Users/williamnapier/.config/yazi/yazi.toml"
"zellij/config.kdl" = "/Users/williamnapier/.config/zellij/config.kdl"
"zellij/layouts/desktop-27-simple.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop-27-simple.kdl"
"zellij/layouts/desktop-27.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop-27.kdl"
"zellij/layouts/desktop-quarters.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop-quarters.kdl"
"zellij/layouts/desktop.kdl" = "/Users/williamnapier/.config/zellij/layouts/desktop.kdl"
"zellij/layouts/laptop.kdl" = "/Users/williamnapier/.config/zellij/layouts/laptop.kdl"
"zellij/layouts/minimal-test.kdl" = "/Users/williamnapier/.config/zellij/layouts/minimal-test.kdl"
"zellij/layouts/test-basic.kdl" = "/Users/williamnapier/.config/zellij/layouts/test-basic.kdl"
"zellij/layouts/test-two-tabs.kdl" = "/Users/williamnapier/.config/zellij/layouts/test-two-tabs.kdl"

[templates]
