[symlinks]
"aerospace/aerospace.toml" = "/Users/williamnapier/.config/aerospace/aerospace.toml"
"ghostty/config" = "/Users/williamnapier/Library/Application Support/com.mitchellh.ghostty/config"
"ghostty/themes/solarized-dark" = "/Users/williamnapier/.config/ghostty/themes/solarized-dark"
"ghostty/themes/solarized-light" = "/Users/williamnapier/.config/ghostty/themes/solarized-light"
"git/gitconfig" = "/Users/williamnapier/.gitconfig"
"helix/config.toml" = "/Users/williamnapier/.config/helix/config.toml"
"karabiner/.DS_Store" = "/Users/williamnapier/.config/karabiner/.DS_Store"
"karabiner/assets/complex_modifications/1690652878.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/1690652878.json"
"karabiner/assets/complex_modifications/1690668710.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/1690668710.json"
"karabiner/assets/complex_modifications/Map physical left_shift key to ` and ~.json" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/Map physical left_shift key to ` and ~.json"
"karabiner/assets/complex_modifications/MouseKeysMod" = "/Users/williamnapier/.config/karabiner/assets/complex_modifications/MouseKeysMod"
"karabiner/automatic_backups/karabiner_20240703.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240703.json"
"karabiner/automatic_backups/karabiner_20240704.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240704.json"
"karabiner/automatic_backups/karabiner_20240727.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240727.json"
"karabiner/automatic_backups/karabiner_20240821.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240821.json"
"karabiner/automatic_backups/karabiner_20240902.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240902.json"
"karabiner/automatic_backups/karabiner_20240912.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20240912.json"
"karabiner/automatic_backups/karabiner_20241107.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20241107.json"
"karabiner/automatic_backups/karabiner_20250326.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250326.json"
"karabiner/automatic_backups/karabiner_20250327.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250327.json"
"karabiner/automatic_backups/karabiner_20250519.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250519.json"
"karabiner/automatic_backups/karabiner_20250520.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250520.json"
"karabiner/automatic_backups/karabiner_20250521.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250521.json"
"karabiner/automatic_backups/karabiner_20250530.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250530.json"
"karabiner/automatic_backups/karabiner_20250531.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250531.json"
"karabiner/automatic_backups/karabiner_20250612.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250612.json"
"karabiner/automatic_backups/karabiner_20250614.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250614.json"
"karabiner/automatic_backups/karabiner_20250617.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250617.json"
"karabiner/automatic_backups/karabiner_20250707.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250707.json"
"karabiner/automatic_backups/karabiner_20250713.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250713.json"
"karabiner/automatic_backups/karabiner_20250811.json" = "/Users/williamnapier/.config/karabiner/automatic_backups/karabiner_20250811.json"
"karabiner/backups/miryoku-setup-20250811-223541/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-223541/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-223633/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-223633/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225243/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225243/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225728/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225728/karabiner-backup.json"
"karabiner/backups/miryoku-setup-20250811-225900/karabiner-backup.json" = "/Users/williamnapier/.config/karabiner/backups/miryoku-setup-20250811-225900/karabiner-backup.json"
"karabiner/karabiner.json" = "/Users/williamnapier/.config/karabiner/karabiner.json"
"nushell/config.nu" = "/Users/williamnapier/.config/nushell/config.nu"
"nushell/env.nu" = "/Users/williamnapier/.config/nushell/env.nu"
"nvim/.DS_Store" = "/Users/williamnapier/.config/nvim/.DS_Store"
"nvim/.git/COMMIT_EDITMSG" = "/Users/williamnapier/.config/nvim/.git/COMMIT_EDITMSG"
"nvim/.git/HEAD" = "/Users/williamnapier/.config/nvim/.git/HEAD"
"nvim/.git/config" = "/Users/williamnapier/.config/nvim/.git/config"
"nvim/.git/description" = "/Users/williamnapier/.config/nvim/.git/description"
"nvim/.git/hooks/applypatch-msg.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/applypatch-msg.sample"
"nvim/.git/hooks/commit-msg.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/commit-msg.sample"
"nvim/.git/hooks/fsmonitor-watchman.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/fsmonitor-watchman.sample"
"nvim/.git/hooks/post-update.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/post-update.sample"
"nvim/.git/hooks/pre-applypatch.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/pre-applypatch.sample"
"nvim/.git/hooks/pre-commit.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/pre-commit.sample"
"nvim/.git/hooks/pre-merge-commit.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/pre-merge-commit.sample"
"nvim/.git/hooks/pre-push.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/pre-push.sample"
"nvim/.git/hooks/pre-rebase.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/pre-rebase.sample"
"nvim/.git/hooks/pre-receive.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/pre-receive.sample"
"nvim/.git/hooks/prepare-commit-msg.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/prepare-commit-msg.sample"
"nvim/.git/hooks/push-to-checkout.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/push-to-checkout.sample"
"nvim/.git/hooks/sendemail-validate.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/sendemail-validate.sample"
"nvim/.git/hooks/update.sample" = "/Users/williamnapier/.config/nvim/.git/hooks/update.sample"
"nvim/.git/index" = "/Users/williamnapier/.config/nvim/.git/index"
"nvim/.git/info/exclude" = "/Users/williamnapier/.config/nvim/.git/info/exclude"
"nvim/.git/logs/HEAD" = "/Users/williamnapier/.config/nvim/.git/logs/HEAD"
"nvim/.git/logs/refs/heads/main" = "/Users/williamnapier/.config/nvim/.git/logs/refs/heads/main"
"nvim/.git/logs/refs/remotes/origin/HEAD" = "/Users/williamnapier/.config/nvim/.git/logs/refs/remotes/origin/HEAD"
"nvim/.git/logs/refs/remotes/origin/main" = "/Users/williamnapier/.config/nvim/.git/logs/refs/remotes/origin/main"
"nvim/.git/objects/3e/80889bcfe993bee0a1841d1ab2c4e64c46a96b" = "/Users/williamnapier/.config/nvim/.git/objects/3e/80889bcfe993bee0a1841d1ab2c4e64c46a96b"
"nvim/.git/objects/47/7805a28d50194d987c9e7bbfaa910ecd2f368a" = "/Users/williamnapier/.config/nvim/.git/objects/47/7805a28d50194d987c9e7bbfaa910ecd2f368a"
"nvim/.git/objects/53/3459c65588d020685485a9281afb36929e2ae7" = "/Users/williamnapier/.config/nvim/.git/objects/53/3459c65588d020685485a9281afb36929e2ae7"
"nvim/.git/objects/7f/9447ab5dc91cb5d97eb749898a98166503294d" = "/Users/williamnapier/.config/nvim/.git/objects/7f/9447ab5dc91cb5d97eb749898a98166503294d"
"nvim/.git/objects/88/52638ee984d8af591bd9cbce10f72fa2313394" = "/Users/williamnapier/.config/nvim/.git/objects/88/52638ee984d8af591bd9cbce10f72fa2313394"
"nvim/.git/objects/92/087ca8f9285112ca9aaaca873996aedca64af0" = "/Users/williamnapier/.config/nvim/.git/objects/92/087ca8f9285112ca9aaaca873996aedca64af0"
"nvim/.git/objects/9c/2a8255b907850a5120370aefeb0720f55d5305" = "/Users/williamnapier/.config/nvim/.git/objects/9c/2a8255b907850a5120370aefeb0720f55d5305"
"nvim/.git/objects/a2/551d8a9e47df9802c8dd0b7f9153274399817a" = "/Users/williamnapier/.config/nvim/.git/objects/a2/551d8a9e47df9802c8dd0b7f9153274399817a"
"nvim/.git/objects/a5/7ff6fc037a1accf11739aad451a2d84e670758" = "/Users/williamnapier/.config/nvim/.git/objects/a5/7ff6fc037a1accf11739aad451a2d84e670758"
"nvim/.git/objects/a8/43ac27847ac442b8eeac5d85ae590f4e3e2c55" = "/Users/williamnapier/.config/nvim/.git/objects/a8/43ac27847ac442b8eeac5d85ae590f4e3e2c55"
"nvim/.git/objects/e8/4ada76947ca588a78c336c7ff525c7b28d3126" = "/Users/williamnapier/.config/nvim/.git/objects/e8/4ada76947ca588a78c336c7ff525c7b28d3126"
"nvim/.git/objects/f5/7a5bdc3e7a9fc7b5c4ae9084b0a4caa05225d4" = "/Users/williamnapier/.config/nvim/.git/objects/f5/7a5bdc3e7a9fc7b5c4ae9084b0a4caa05225d4"
"nvim/.git/objects/pack/pack-29f7d177b05a3d32a9ff811b4d091d2dd5404730.idx" = "/Users/williamnapier/.config/nvim/.git/objects/pack/pack-29f7d177b05a3d32a9ff811b4d091d2dd5404730.idx"
"nvim/.git/objects/pack/pack-29f7d177b05a3d32a9ff811b4d091d2dd5404730.pack" = "/Users/williamnapier/.config/nvim/.git/objects/pack/pack-29f7d177b05a3d32a9ff811b4d091d2dd5404730.pack"
"nvim/.git/objects/pack/pack-29f7d177b05a3d32a9ff811b4d091d2dd5404730.rev" = "/Users/williamnapier/.config/nvim/.git/objects/pack/pack-29f7d177b05a3d32a9ff811b4d091d2dd5404730.rev"
"nvim/.git/packed-refs" = "/Users/williamnapier/.config/nvim/.git/packed-refs"
"nvim/.git/refs/heads/main" = "/Users/williamnapier/.config/nvim/.git/refs/heads/main"
"nvim/.git/refs/remotes/origin/HEAD" = "/Users/williamnapier/.config/nvim/.git/refs/remotes/origin/HEAD"
"nvim/.git/refs/remotes/origin/main" = "/Users/williamnapier/.config/nvim/.git/refs/remotes/origin/main"
"nvim/.github/ISSUE_TEMPLATE/bug_report.md" = "/Users/williamnapier/.config/nvim/.github/ISSUE_TEMPLATE/bug_report.md"
"nvim/.github/pull_request_template.md" = "/Users/williamnapier/.config/nvim/.github/pull_request_template.md"
"nvim/.github/workflows/stylua.yml" = "/Users/williamnapier/.config/nvim/.github/workflows/stylua.yml"
"nvim/.gitignore" = "/Users/williamnapier/.config/nvim/.gitignore"
"nvim/.stylua.toml" = "/Users/williamnapier/.config/nvim/.stylua.toml"
"nvim/LICENSE.md" = "/Users/williamnapier/.config/nvim/LICENSE.md"
"nvim/README.md" = "/Users/williamnapier/.config/nvim/README.md"
"nvim/doc/kickstart.txt" = "/Users/williamnapier/.config/nvim/doc/kickstart.txt"
"nvim/doc/tags" = "/Users/williamnapier/.config/nvim/doc/tags"
"nvim/init.lua" = "/Users/williamnapier/.config/nvim/init.lua"
"nvim/init.lua.backup-20250811-185641" = "/Users/williamnapier/.config/nvim/init.lua.backup-20250811-185641"
"nvim/last_session.vim" = "/Users/williamnapier/.config/nvim/last_session.vim"
"nvim/lazy-lock.json" = "/Users/williamnapier/.config/nvim/lazy-lock.json"
"nvim/lua/custom/.DS_Store" = "/Users/williamnapier/.config/nvim/lua/custom/.DS_Store"
"nvim/lua/custom/plugins/init.lua" = "/Users/williamnapier/.config/nvim/lua/custom/plugins/init.lua"
"nvim/lua/debug_telescope.lua" = "/Users/williamnapier/.config/nvim/lua/debug_telescope.lua"
"nvim/lua/ghostty-yazi.lua" = "/Users/williamnapier/.config/nvim/lua/ghostty-yazi.lua"
"nvim/lua/health/kickstart.lua" = "/Users/williamnapier/.config/nvim/lua/health/kickstart.lua"
"nvim/lua/kickstart.nvim/plugins/autopairs.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/autopairs.lua"
"nvim/lua/kickstart.nvim/plugins/debug.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/debug.lua"
"nvim/lua/kickstart.nvim/plugins/gitsigns.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/gitsigns.lua"
"nvim/lua/kickstart.nvim/plugins/indent_line.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/indent_line.lua"
"nvim/lua/kickstart.nvim/plugins/lint.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/lint.lua"
"nvim/lua/kickstart.nvim/plugins/neo-tree.lua" = "/Users/williamnapier/.config/nvim/lua/kickstart.nvim/plugins/neo-tree.lua"
"nvim/lua/plugins/anki.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/anki.lua"
"nvim/lua/plugins/auto-save.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/auto-save.lua"
"nvim/lua/plugins/link-validator.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/link-validator.lua"
"nvim/lua/plugins/prose.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/prose.lua"
"nvim/lua/plugins/telekasten.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua"
"nvim/lua/plugins/telekasten.lua.backup-20250811-185650" = "/Users/williamnapier/.config/nvim/lua/plugins/telekasten.lua.backup-20250811-185650"
"nvim/lua/plugins/yazi.lua" = "/Users/williamnapier/.config/nvim/lua/plugins/yazi.lua"
"nvim/lua/telescope_filter_debug.lua" = "/Users/williamnapier/.config/nvim/lua/telescope_filter_debug.lua"
"nvim/spell/en.utf-8.add" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add"
"nvim/spell/en.utf-8.add.spl" = "/Users/williamnapier/.config/nvim/spell/en.utf-8.add.spl"
"nvim/telescope_debug.lua" = "/Users/williamnapier/.config/nvim/telescope_debug.lua"
"shell/zshrc" = "/Users/williamnapier/.zshrc"
"sketchybar/colors.sh" = "/Users/williamnapier/.config/sketchybar/colors.sh"
"sketchybar/items/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/items/aerospace.sh"
"sketchybar/items/battery.sh" = "/Users/williamnapier/.config/sketchybar/items/battery.sh"
"sketchybar/items/calendar.sh" = "/Users/williamnapier/.config/sketchybar/items/calendar.sh"
"sketchybar/items/clock.sh" = "/Users/williamnapier/.config/sketchybar/items/clock.sh"
"sketchybar/items/cpu.sh" = "/Users/williamnapier/.config/sketchybar/items/cpu.sh"
"sketchybar/items/front_app.sh" = "/Users/williamnapier/.config/sketchybar/items/front_app.sh"
"sketchybar/items/spaces.sh" = "/Users/williamnapier/.config/sketchybar/items/spaces.sh"
"sketchybar/items/volume.sh" = "/Users/williamnapier/.config/sketchybar/items/volume.sh"
"sketchybar/plugins/aerospace.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace.sh"
"sketchybar/plugins/aerospace_windows.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace_windows.sh"
"sketchybar/plugins/aerospace_workspace_tracker.sh" = "/Users/williamnapier/.config/sketchybar/plugins/aerospace_workspace_tracker.sh"
"sketchybar/plugins/battery.sh" = "/Users/williamnapier/.config/sketchybar/plugins/battery.sh"
"sketchybar/plugins/calendar.sh" = "/Users/williamnapier/.config/sketchybar/plugins/calendar.sh"
"sketchybar/plugins/clock.sh" = "/Users/williamnapier/.config/sketchybar/plugins/clock.sh"
"sketchybar/plugins/cpu.sh" = "/Users/williamnapier/.config/sketchybar/plugins/cpu.sh"
"sketchybar/plugins/front_app.sh" = "/Users/williamnapier/.config/sketchybar/plugins/front_app.sh"
"sketchybar/plugins/icon_map_fn.sh" = "/Users/williamnapier/.config/sketchybar/plugins/icon_map_fn.sh"
"sketchybar/plugins/volume.sh" = "/Users/williamnapier/.config/sketchybar/plugins/volume.sh"
"sketchybar/sketchybarrc" = "/Users/williamnapier/.config/sketchybar/sketchybarrc"
"wezterm/wezterm.lua" = "/Users/williamnapier/.config/wezterm/wezterm.lua"
"yazi/keymap.toml" = "/Users/williamnapier/.config/yazi/keymap.toml"
"yazi/yazi.toml" = "/Users/williamnapier/.config/yazi/yazi.toml"

[templates]
