# Cross-platform inlyne configuration
# Larger scale factor for better readability
scale = 2.0

# Force dark theme (Auto detection doesn't work reliably on Niri)
theme = "Dark"

# Smooth scrolling
lines-to-scroll = 3.0

[dark-theme]
# Regular text color (Solarized base0)
text-color = 0x839496
# Background canvas color (Solarized base03 - the characteristic dark blue/teal!)
background-color = 0x002b36
# Inline code text color (Solarized cyan)
code-color = 0x2aa198
# Quote block background color (Solarized base02)
quote-block-color = 0x073642
# Hyperlink text color (Solarized blue)
link-color = 0x268bd2
# Text selection color (Solarized base02 for subtle highlight)
select-color = 0x073642
# Checkbox ticked background color (bright green for visibility!)
checkbox-color = 0x2ecc71
# Solarized Dark syntax highlighting
code-highlighter = "solarized-dark"

[light-theme]
text-color = 0x000000
background-color = 0xffffff
code-color = 0x95114e
quote-block-color = 0xeef9fe
link-color = 0x5466ff
select-color = 0xcde8f0
# Checkbox ticked background color (bright green!)
checkbox-color = 0x27ae60
code-highlighter = "solarized-light"

[font-options]
# JetBrains Mono Nerd Font for consistent display across platforms
regular-font = "JetBrainsMono Nerd Font"
monospace-font = "JetBrainsMono Nerd Font Mono"
